name: Sync starters/chrome/ to KudoAI/chatgpt.js-chrome-starter/

on:
  push:
    branches: [main]
    paths: [starters/chrome/**]

jobs:
  build:
    if: (github.repository == 'KudoAI/chatgpt.js') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout KudoAI/chatgpt.js
        uses: actions/checkout@v6.0.1
        with:
          path: KudoAI/chatgpt.js

      - name: Checkout KudoAI/chatgpt.js-chrome-starter
        uses: actions/checkout@v6.0.1
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/chatgpt.js-chrome-starter
          path: KudoAI/chatgpt.js-chrome-starter

      - name: Sync starters/chrome/ to KudoAI/chatgpt.js-chrome-starter/
        run: |
          rsync -avhc --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            "${{ github.workspace }}/KudoAI/chatgpt.js/starters/chrome/" \
            "${{ github.workspace }}/KudoAI/chatgpt.js-chrome-starter/"

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          DELIM="EOF_$(uuidgen)"
          echo "ESCAPED_MSG<<$DELIM" >> "$GITHUB_ENV"
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> "$GITHUB_ENV"
          echo "$DELIM" >> "$GITHUB_ENV"

      - name: Config committer
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_ID: ${{ secrets.GPG_PRIVATE_ID }}
        run: |
          gpg --batch --import <(echo "$GPG_PRIVATE_KEY")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "$GPG_PRIVATE_ID"

      - name: Push changes to KudoAI/chatgpt.js-chrome-starter
        run: |
          cd ${{ github.workspace }}/KudoAI/chatgpt.js-chrome-starter
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG â†ž [auto-sync from https://github.com/KudoAI/chatgpt.js]" || true
          git push
